void* thread_func(void* _args);
void dense(int input, int output, float *x, float*w, float* b, int a, float* y);
void dropout(float p, int flag, int *mask, float* x, float* output, int size);
void lstm(float* w_x, float* w_m, float* w_c,float* x, float* last_m, float* last_c, float*b_x, int size_x, float* container, float* w_fx, float* w_fm, float* w_fc, float* b_fx, float* container2, float* w_cx, float* w_cm, float* b_cx, float* container3, float* w_ox, float* w_om, float* w_oc, float* b_ox, float* container4,float* zi, float* zf, float* zg, float* zo, float* o, float*f, float* it);
void train(float** music, float** dw, float** db, int thread, int lunghezza_brano);
void lstm_backpropagation(int flag, float** matrix,float* c1, float* c2, float* c3, float* c4, float* dc_t1);
void save_params(float** matrix, float** dw, float** db,int thread);
void free_matrix(float** m, int rows);
float random_general_gaussian(float mean, float dev);
int shuffle_training_set_in_vector(char** m,int n);
int read_files(char** name);
void free_char_matrix(char** m, int rows);
void load_network();
int save_network(int epoch);
void print_matrix(float* m, int row, int cols);
void clipping_gradients(float thereshold,float** dw,float** db);
